export const productData=[
    {
        name:"Lenevo computer",
        description:"Prodouct1 dnoekndckdcdsnkcndsncknsnckndcndncdncndncdnjcn",
        count:3,
        price:362,
        category:"Tables",
        images:[
            {
                path:"https://source.unsplash.com/random/900×700/?"
            },
            {
                path:"https://source.unsplash.com/random/900×700/?"
            },
            {
                path:"https://source.unsplash.com/random/900×700/?"
            }
        ],
        rating:2,
        reviewsNumber:5,
        reviews:[],
        attrs:[{key:"color",value:"blue"}],
    },
    {
        name:"Predator",
        description:"Prodouct2 dnoekndckdcdsnkcndsncknsnckndcndncdncndncdnjcn",
        count:5,
        price:425,
        category:"Monitors",
        images:[
            {
                path:"https://source.unsplash.com/random/900×700/?"
            },
            {
                path:"https://source.unsplash.com/random/900×700/?"
            },
            {
                path:"https://source.unsplash.com/random/900×700/?"
            }
        ],
        rating:5,
        reviewsNumber:5,
        reviews:[],
        attrs:[{key:"color",value:"blue"}],
    },
    {
        name:"Dell",
        description:"Prodouct3 dnoekndckdcdsnkcndsncknsnckndcndncdncndncdnjcn",
        count:5,
        price:2500,
        category:"Computers",
        images:[
            {
                path:"https://source.unsplash.com/random/900×700/?laptop"
            },
            {
                path:"https://source.unsplash.com/random/900×700/?dog"
            },
            {
                path:"https://source.unsplash.com/random/900×700/?car"
            }
        ],
        rating:4,
        reviewsNumber:5,
        reviews:[],
        attrs:[{key:"color",value:"blue"}],
    },
    {
        name:"Apple",
        description:"Prodouct3 dnoekndckdcdsnkcndsncknsnckndcndncdncndncdnjcn",
        count:5,
        price:26000,
        category:"Fruits",
        images:[
            {
                path:"https://source.unsplash.com/random/900×700/?"
            },
            {
                path:"https://source.unsplash.com/random/900×700/?"
            },
            {
                path:"https://source.unsplash.com/random/900×700/?"
            }
        ],
        rating:3,
        reviewsNumber:5,
        reviews:[],
        attrs:[{key:"color",value:"blue"}],
    },
]